apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bytewedge.fullname" . }}-injector
  labels:
    bytewedge: injector
    {{- include "bytewedge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.injector.replicaCount }}
  selector:
    matchLabels:
      bytewedge: injector
      {{- include "bytewedge.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        bytewedge: injector
        {{- include "bytewedge.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "bytewedge.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: injector-postgresql-ready
          {{- with .Values.postgresql }}
          image: {{ .image }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          env:
          - name: PGPASSWORD
            value: secret
          - name: PGUSER
            value: postgres
          - name: PGHOST
            value: postgresql
          command: ["sh", "-c"] 
          args: ["until psql -d bytewedge -c '\\q'; \
                  do \
                  echo 'waiting bytewedge postgresql'; \
                  sleep 5;
                  done"]
        - name: injector-cockroachdb-ready
          {{- with .Values.postgresql }}
          image: {{ .image }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          command: ["sh", "-c"]
          args: ["until psql postgres://blob@{{ .Release.Name }}-cockroachdb-public:26257/blob?sslmode=disable -c '\\q'; \
                  do \
                  echo 'waiting cockroachdb {{ .Release.Name }}-cockroachdb-public'; \
                  sleep 5;
                  done"]
      containers:
        - name: {{ .Chart.Name }}-injector
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.image }}
          image: "{{ .repository }}-injector:{{ .tag }}"
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          command:
          - /usr/local/bin/bytewedge-injector
          args:
          - -blob
          - "postgres://blob@{{ .Release.Name }}-cockroachdb-public:26257/blob?sslmode=disable"
          - -meta
          {{- with .Values.postgresql }}
          - "postgres://postgres:secret@{{ .host }}:{{ .port }}/bytewedge?sslmode=require"
          {{- end }}
          - -port
          - {{ .Values.injector.port | quote }}
          - -dir
          - /logs
          workingDir: /logs
          volumeMounts:
          - mountPath: /logs
            name: app-logs
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          ports:
            - name: http
              containerPort: {{ .Values.injector.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - emptyDir: {}
        name: app-logs
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
