apiVersion: v1
kind: Service
metadata:
  name: {{ include "bytewedge.fullname" . }}-injector
  labels:
    bytewedge: injector
    {{- include "bytewedge.labels" . | nindent 4 }}
spec:
  {{- with .Values.injector }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: http
  {{- end }}
  sessionAffinity: None
  type: ClusterIP
  selector:
    bytewedge: injector
    {{- include "bytewedge.selectorLabels" . | nindent 4 }}
