{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bytewedge.serviceAccountName" . }}
  labels:
{{ include "bytewedge.labels" . | nindent 4 }}
{{- end -}}
