{{- $svcRelName := .Values.helm.name -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: bytewedge-ddl
  labels:
    {{- include "jobs.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      name: {{ include "jobs.fullname" . }}
      labels:
        {{- include "jobs.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "jobs.serviceAccountName" . }}
      initContainers:
        {{- with .Values.postgresql }}
        - name: bytewedge-job-init
          image: {{ .image }}
          command: ["sh"]
          args: ["-c", "until pg_isready -h {{ $svcRelName }}-{{ .host }}; \
                        do \
                        echo 'Waiting for postgres at: {{ .host }}'; \
                        sleep 2; \
                        done"]
        {{- end }}
      containers:
        - name: bytewedge-ddl
          image: "{{ .Values.image.repository }}-jobs:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/bytewedge-jobs
            - -comp
            - bytewedge
            - -host
            - "{{ $svcRelName }}-{{ .Values.postgresql.host }}"
      restartPolicy: Never
