apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-config
data:
  relay: |-
    receivers:
      opencensus:
        endpoint: 0.0.0.0:55678
      jaeger:
        protocols:
          thrift-http:
            endpoint: 0.0.0.0:{{ .Values.otelcol.port }}
    
    exporters:
      relay:
        url: "http://wedge:{{ .Values.wedge.port }}/upload"
        interval: 0
        format: json
      logging:
        loglevel: debug
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: promexample
        const_labels:
          label1: value
    
    processors:
      batch:
      queued_retry:
    
    extensions:
      pprof:
        endpoint: localhost:1777
      zpages:
        endpoint: localhost:55679
      health_check:
    
    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [opencensus, jaeger]
          exporters: [relay]
          processors: [batch, queued_retry]
        #metrics:
          #receivers: [opencensus]
          #exporters: [prometheus]