injector:
  replicaCount: 2
  resources:
    limits:
      memory: 2Gi

web:
  replicaCount: 2
  resources:
    limits:
      memory: 5Gi

query:
  replicaCount: 3
  # unit of GB
  cache: 10
  ratio: 1
  resources:
    limits:
      memory: 12Gi
    requests:
      cpu: 10
      memory: 10Gi

# dependencies start
timescaledb-single:
  replicaCount: 2
  persistentVolumes:
    data:
      size: 20Gi
    wal:
      size: 20Gi
  resources:
    requests:
      memory: 3Gi

cockroachdb:
  statefulset:
    # at least 3
    replicas: 3
    resources:
      requests:
        memory: 3Gi
    podAntiAffinity:
      # Type of anti-affinity rules: either `soft`, `hard` or empty value (which
      # disables anti-affinity rules).
      type: hard
  storage:
    persistentVolume:
      size: 50Gi
