query:
  replicaCount: 5
  # unit of GB
  cache: 10
  resources:
    requests:
      cpu: 3
      memory: 10Gi
# dependencies start
timescaledb-single:
  persistentVolumes:
    data:
      size: 20Gi
    wal:
      size: 20Gi
  resources:
    requests:
      memory: 4Gi

cockroachdb:
  statefulset:
    # at least 3
    replicas: 5
    resources:
      requests:
        memory: 2Gi
  storage:
    persistentVolume:
      size: 50Gi
